#!/bin/bash

# Quick build with fpm - https://github.com/jordansissel/fpm/

NAME=qzip
VERSION=1.5.0
ITERATION=1.custom
BUILD=/tmp/$NAME
TARGET=deb

which fpm > /dev/null
if [ $? -ne 0 ]; then
  echo "Can't find fpm, is it installed?"
  exit 1
fi

if [ -d $BUILD ]; then
  rm -rf $BUILD
fi

export PREFIX=$BUILD/usr/local

./configure -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX 
make install

if [ ! -d pkg ]; then
  mkdir pkg
fi

rm -f pkg/$NAME-$VERSION*.$TARGET pkg/$NAME\_$VERSION*.$TARGET

cd pkg

echo "#!/bin/bash
ldconfig" > $BUILD/afterinstall

echo "#!/bin/bash
ldconfig" > $BUILD/afterremove

mkdir -p $BUILD/etc/ld.so.conf.d
echo "/usr/local/lib" > $BUILD/etc/ld.so.conf.d/libquicklz.conf

fpm -s dir -t $TARGET -C $BUILD --name $NAME --version $VERSION --iteration $ITERATION \
  --after-install $BUILD/afterinstall --after-remove $BUILD/afterremove \
  --license GPLv2 --maintainer "<matthew@37signals.com>" --vendor "QuickLZ" \
  --url "https://github.com/mdkent/quicklz" \
  --description "A very fast implementation of LZO compressors" \
  etc usr
